import { NextRequest, NextResponse } from 'next/server';
import { FilterQuery } from 'mongoose';
import { revalidateTag } from 'next/cache';
import { connectToDatabase } from '@/lib/mongodb';
import Product, { IProduct } from '@/models/Product';
import { getSessionFromCookies } from '@/lib/auth';
import { getStockStatus } from '@/lib/utils';
import { PRODUCTS_TAG } from '@/lib/data';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

// Lean products miss virtuals — compute them deterministically here.
type LeanProduct = Record<string, unknown> & {
  variants?: { size: string; stock: number }[];
};

function withComputed<T extends LeanProduct>(p: T) {
  const totalStock = (p.variants ?? []).reduce((s, v) => s + (v.stock ?? 0), 0);
  return {
    ...p,
    _id: String(p._id),
    totalStock,
    stockStatus: getStockStatus(totalStock),
  };
}

// GET /api/products — list with filtering, sorting, search.
// Public consumers only see active products; admins can pass ?all=true.
export async function GET(request: NextRequest) {
  try {
    await connectToDatabase();
    const { searchParams } = new URL(request.url);

    const all = searchParams.get('all') === 'true';
    const authed = all ? await getSessionFromCookies() : false;

    const query: FilterQuery<IProduct> = {};

    // Storefront only sees active products
    if (!(all && authed)) {
      query.status = 'active';
    } else {
      const status = searchParams.get('status');
      if (status === 'active' || status === 'draft') query.status = status;
    }

    const category = searchParams.get('category');
    const fabric = searchParams.get('fabric');
    const fit = searchParams.get('fit');
    const sport = searchParams.get('sport');
    const featured = searchParams.get('featured');
    const search = searchParams.get('search');
    const size = searchParams.get('size');

    if (category) query.category = category;
    if (fabric) query.fabric = fabric;
    if (fit) query.fit = fit;
    if (sport) query.sport = sport;
    if (featured === 'true') query.featured = true;
    if (size) query['variants.size'] = size;
    if (search) {
      query.title = { $regex: search.trim(), $options: 'i' };
    }

    // Sorting
    const sort = searchParams.get('sort');
    let sortObj: Record<string, 1 | -1> = { createdAt: -1 };
    if (sort === 'price-asc') sortObj = { price: 1 };
    else if (sort === 'price-desc') sortObj = { price: -1 };

    const limit = Math.min(Number(searchParams.get('limit')) || 100, 200);

    const raw = await Product.find(query).sort(sortObj).limit(limit).lean();
    let products = raw.map((p) => withComputed(p as LeanProduct));

    // In-stock filter (computed from variants — applied post-query)
    if (searchParams.get('inStock') === 'true') {
      products = products.filter((p) => p.totalStock > 0);
    }

    return NextResponse.json({ products });
  } catch (err) {
    console.error('GET /api/products error:', err);
    return NextResponse.json(
      { error: 'Failed to fetch products.' },
      { status: 500 }
    );
  }
}

// POST /api/products — create a product (admin only)
export async function POST(request: NextRequest) {
  const authed = await getSessionFromCookies();
  if (!authed) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    await connectToDatabase();
    const body = await request.json();

    const {
      title,
      price,
      images,
      category,
      fabric,
      fit,
      sport,
      variants,
      status,
      featured,
    } = body;

    if (!title || price == null || !category || !fabric || !fit || !sport) {
      return NextResponse.json(
        { error: 'Missing required fields.' },
        { status: 400 }
      );
    }

    if (!Array.isArray(images) || images.length === 0) {
      return NextResponse.json(
        { error: 'At least one product image is required.' },
        { status: 400 }
      );
    }

    if (!Array.isArray(variants) || variants.length === 0) {
      return NextResponse.json(
        { error: 'At least one size variant is required.' },
        { status: 400 }
      );
    }

    // slug auto-generated by pre-save hook
    const product = await Product.create({
      title,
      slug: 'pending',
      price,
      images,
      category,
      fabric,
      fit,
      sport,
      variants,
      status: status ?? 'draft',
      featured: featured ?? false,
    });

    revalidateTag(PRODUCTS_TAG);

    return NextResponse.json(
      { product: product.toJSON({ virtuals: true }) },
      { status: 201 }
    );
  } catch (err) {
    console.error('POST /api/products error:', err);    return NextResponse.json(
      { error: 'Failed to create product.' },
      { status: 500 }
    );
  }
}
